package com.flogin.entity;

import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * Product Entity - Represents a product in the e-commerce system
 * 
 * <p>This JPA entity maps to the "products" table in the database.
 * Stores complete product information including pricing, inventory,
 * categorization, and detailed descriptions.</p>
 * 
 * <p>Database Schema:</p>
 * <pre>
 * Table: products
 * Columns:
 *   - id (BIGINT, Primary Key, Auto-increment)
 *   - product_name (VARCHAR(100), Not Null)
 *   - price (DOUBLE, Not Null)
 *   - quantity (INTEGER, Not Null)
 *   - category (VARCHAR(50), Not Null, Enum)
 *   - description (VARCHAR(500))
 * </pre>
 * 
 * <p>Business Rules:</p>
 * <ul>
 *   <li>Product name must be unique across all products</li>
 *   <li>Price must be positive (> 0)</li>
 *   <li>Quantity must be non-negative (>= 0)</li>
 *   <li>Category must be one of predefined enum values</li>
 *   <li>Description is optional but recommended</li>
 * </ul>
 * 
 * <p>Category Enum Values:</p>
 * <ul>
 *   <li>ELECTRONICS - Electronic devices and gadgets</li>
 *   <li>BOOKS - Books and reading materials</li>
 *   <li>CLOTHING - Clothing and apparel</li>
 *   <li>TOYS - Toys and games</li>
 *   <li>GROCERIES - Food and grocery items</li>
 * </ul>
 * 
 * <p>JPA Features:</p>
 * <ul>
 *   <li>@Enumerated(EnumType.STRING) - Stores enum as string in database</li>
 *   <li>Auto-generated ID with IDENTITY strategy</li>
 *   <li>Column length constraints for data integrity</li>
 *   <li>Support for both enum and string setters for flexibility</li>
 * </ul>
 * 
 * @author Software Testing Team
 * @version 1.0
 * @since 2025-11-26
 * @see Category
 * @see jakarta.persistence.Entity
 */
@Entity
@Table(name = "products")
public class Product {
    
    /**
     * Product's unique identifier (Primary Key)
     * Auto-generated by database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private long id;
    
    /**
     * Product price in USD
     * Must be positive value (> 0)
     * Cannot be null
     */
    @Column(name = "price", nullable = false)
    private double price;
    
    /**
     * Product name/title
     * Maximum length: 100 characters
     * Must be unique (enforced at service level)
     * Cannot be null
     */
    @Column(name = "product_name", nullable = false, length = 100)
    private String productName;
    
    /**
     * Available quantity in inventory
     * Must be non-negative integer (>= 0)
     * Cannot be null
     */
    @Column(name = "quantity", nullable = false)
    private Integer quantity;
    
    /**
     * Product description/details
     * Maximum length: 500 characters
     * Optional field (can be null)
     */
    @Column(name = "description", length = 500)
    private String description;
    
    /**
     * Product category (enum stored as string)
     * 
     * <p>Stored as VARCHAR in database but mapped to Category enum in Java.
     * This provides type safety in code while maintaining flexibility in database.</p>
     * 
     * <p>Cannot be null - every product must have a category</p>
     * 
     * @see Category
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 50)
    private Category category;

    /**
     * Default constructor (required by JPA)
     * 
     * <p>JPA requires a no-argument constructor for entity instantiation.
     * Used when loading entities from database.</p>
     */
    public Product() {
    }

    /**
     * Constructor with all fields (using Category enum)
     * 
     * <p>Recommended constructor for type-safe product creation.
     * Accepts Category enum directly to ensure valid category values.</p>
     * 
     * @param id Product unique identifier
     * @param category Product category (enum)
     * @param description Product description
     * @param quantity Available quantity
     * @param productName Product name
     * @param price Product price
     */
    public Product(long id, Category category, String description, Integer quantity, String productName, double price) {
        this.id = id;
        this.category = category;
        this.description = description;
        this.quantity = quantity;
        this.productName = productName;
        this.price = price;
    }

    /**
     * Constructor with string category (backward compatibility)
     * 
     * <p>Alternative constructor that accepts category as String and converts
     * to enum. Useful for API requests or legacy code compatibility.</p>
     * 
     * <p>Will throw IllegalArgumentException if category string is invalid.</p>
     * 
     * @param id Product unique identifier
     * @param category Product category as string (e.g., "Electronics")
     * @param description Product description
     * @param quantity Available quantity
     * @param productName Product name
     * @param price Product price
     * @throws IllegalArgumentException if category is not valid
     */
    public Product(long id, String category, String description, Integer quantity, String productName, double price) {
        this.id = id;
        this.category = Category.fromString(category);
        this.description = description;
        this.quantity = quantity;
        this.productName = productName;
        this.price = price;
    }

    // ============ Getters and Setters ============
    // Standard JavaBean accessor methods with JavaDoc
    
    /**
     * Get product ID
     * @return Product's unique identifier
     */
    public long getId() {
        return id;
    }

    /**
     * Set product ID
     * @param id Product's unique identifier
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Get product category (enum)
     * @return Product category enum value
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Set product category (enum - type safe)
     * 
     * <p>Recommended method for setting category as it provides type safety.</p>
     * 
     * @param category Product category enum value
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * Set product category from string (backward compatibility)
     * 
     * <p>Convenience method that accepts string and converts to enum.
     * Useful for API requests where category comes as string.</p>
     * 
     * @param category Product category as string (e.g., "Electronics")
     * @throws IllegalArgumentException if category string is invalid
     */
    public void setCategory(String category) {
        this.category = Category.fromString(category);
    }

    /**
     * Get product description
     * @return Product description text
     */
    public String getDescription() {
        return description;
    }

    /**
     * Set product description
     * @param description Product description (max 500 characters)
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Get available quantity
     * @return Number of items in stock
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * Set available quantity
     * @param quantity Number of items in stock (must be >= 0)
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * Get product name
     * @return Product name/title
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Set product name
     * @param productName Product name (must be unique, max 100 characters)
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Get product price
     * @return Product price in USD
     */
    public double getPrice() {
        return price;
    }

    /**
     * Set product price
     * @param price Product price (must be > 0)
     */
    public void setPrice(double price) {
        this.price = price;
    }
}
