package com.flogin.entity;

import jakarta.persistence.*;

/**
 * User Entity - Represents a user in the system
 * @author Software Testing Team
 * @version 1.0
 * @since 2025-11-26
 * @see jakarta.persistence.Entity
 */
@Entity
@Table(name = "users")
public class User {
    
    /**
     * User's unique identifier (Primary Key)
     * Auto-generated by database using IDENTITY strategy
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    
    /**
     * User's login username
     * Must be unique across all users
     * Maximum length: 50 characters
     * Cannot be null
     */
    @Column(name = "user_name", unique = true, nullable = false, length = 50)
    private String userName;
    
    /**
     * User's email address
     * Must be unique across all users
     * Maximum length: 100 characters
     * Cannot be null
     */
    @Column(name = "email", unique = true, nullable = false, length = 100)
    private String email;
    
    /**
     * User's password (BCrypt hashed)
     */
    @Column(name = "hash_password", nullable = false, length = 255)
    private String hashPassword;

    /**
     * Default constructor (required by JPA)
     */
    public User() {
    }

    /**
     * Constructor with all fields
     * @param id User's unique identifier
     * @param userName User's login username
     * @param hashPassword BCrypt hashed password
     * @param email User's email address
     */
    public User(Long id, String userName, String hashPassword, String email) {
        this.hashPassword = hashPassword;
        this.email = email;
        this.id = id;
        this.userName = userName;
    }

    // ============ Getters and Setters ============
    // Standard JavaBean accessor methods
    
    /**
     * Get user ID
     * @return User's unique identifier
     */
    public Long getId() {
        return id;
    }

    /**
     * Set user ID
     * @param id User's unique identifier
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Get username
     * @return User's login username
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Set username
     * @param userName User's login username (must be unique)
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Get hashed password
     * @return BCrypt hashed password
     */
    public String getHashPassword() {
        return hashPassword;
    }

    /**
     * Set hashed password
     * @param hashPassword BCrypt hashed password (not plain text)
     */
    public void setHashPassword(String hashPassword) {
        this.hashPassword = hashPassword;
    }
    
    /**
     * Get email address
     * @return User's email address
     */
    public String getEmail() {
        return email;
    }
    
    /**
     * Set email address
     * @param email User's email address (must be unique)
     */
    public void setEmail(String email) {
        this.email = email;
    }
}
