package com.flogin.dto.ProductDtos;

import jakarta.validation.constraints.*;

/**
 * CreateProductRequest - Data Transfer Object for Product Creation
 * 
 * Purpose:
 * This DTO encapsulates the data required to create a new product in the system.
 * It serves as the request body for the POST /api/products endpoint and enforces
 * business rules through Jakarta Bean Validation.
 * 
 * Design Pattern: Command Object / Request DTO
 * - Separates API request from domain model
 * - Provides validation at API boundary
 * - Prevents over-posting attacks
 * - Documents required fields for product creation
 * 
 * Key Difference from ProductDto:
 * - No 'id' field (ID is auto-generated by database)
 * - Used only for CREATE operations
 * - Focused on input validation
 * - Cannot be used for updates (use UpdateProductRequest instead)
 * 
 * Validation Rules:
 * 
 * productName Field:
 * - @NotBlank: Cannot be null, empty, or whitespace only
 * - @Size(min=3, max=100): Length between 3 and 100 characters
 * 
 * Valid Examples:
 * - "Laptop Dell XPS 15" ✓
 * - "iPhone 15 Pro Max" ✓
 * - "Bàn phím cơ Gaming" ✓
 * 
 * Invalid Examples:
 * - "AB" ✗ (too short, less than 3 chars)
 * - "" ✗ (empty string)
 * - "   " ✗ (whitespace only)
 * - "A very long product name that exceeds one hundred characters limit..." ✗ (>100 chars)
 * 
 * price Field:
 * - @NotNull: Cannot be null
 * - @DecimalMin("0.01"): Must be greater than 0
 * - @DecimalMax("999999999"): Cannot exceed 999,999,999
 * 
 * Valid Examples:
 * - 99.99 ✓
 * - 15000000.00 ✓ (15 million VND)
 * - 0.01 ✓ (minimum valid price)
 * 
 * Invalid Examples:
 * - 0.00 ✗ (must be positive)
 * - -100.00 ✗ (negative price)
 * - null ✗ (required field)
 * - 1000000000.00 ✗ (exceeds maximum)
 * 
 * description Field:
 * - @Size(max=500): Optional, but if provided, max 500 characters
 * - Can be null or empty (optional field)
 * 
 * Valid Examples:
 * - "Đây là mô tả sản phẩm" ✓
 * - null ✓ (optional)
 * - "" ✓ (empty allowed)
 * 
 * Invalid Examples:
 * - "Very long description..." (>500 chars) ✗
 * 
 * quantity Field:
 * - @NotNull: Cannot be null
 * - @Min(0): Must be non-negative (0 or positive)
 * - @Max(99999): Cannot exceed 99,999 units
 * 
 * Valid Examples:
 * - 0 ✓ (out of stock is valid)
 * - 100 ✓
 * - 99999 ✓ (maximum)
 * 
 * Invalid Examples:
 * - -1 ✗ (negative quantity)
 * - 100000 ✗ (exceeds maximum)
 * - null ✗ (required)
 * 
 * category Field:
 * - @NotBlank: Cannot be null, empty, or whitespace
 * - Must match one of the valid Category enum values:
 *   * "Điện tử" (Electronics)
 *   * "Thời trang" (Fashion)
 *   * "Thực phẩm" (Food)
 *   * "Đồ gia dụng" (Home Appliances)
 *   * "Sách" (Books)
 * 
 * Valid Examples:
 * - "Điện tử" ✓
 * - "Thời trang" ✓
 * 
 * Invalid Examples:
 * - "Invalid Category" ✗ (not in enum)
 * - "" ✗ (empty)
 * - null ✗ (required)
 * 
 * JSON Request Example:
 * <pre>
 * {
 *   "productName": "Laptop Dell XPS 15",
 *   "price": 25000000.00,
 *   "description": "Laptop cao cấp cho lập trình viên",
 *   "quantity": 50,
 *   "category": "Điện tử"
 * }
 * </pre>
 * 
 * Validation Error Response (400 BAD REQUEST):
 * <pre>
 * {
 *   "message": "Validation failed",
 *   "errors": [
 *     "Product Name phải từ 3 đến 100 ký tự",
 *     "Price phải > 0",
 *     "Category không được rỗng"
 *   ]
 * }
 * </pre>
 * 
 * Success Response (201 CREATED):
 * <pre>
 * {
 *   "id": 12345,
 *   "productName": "Laptop Dell XPS 15",
 *   "price": 25000000.00,
 *   "description": "Laptop cao cấp cho lập trình viên",
 *   "quantity": 50,
 *   "category": "Điện tử"
 * }
 * </pre>
 * 
 * Usage in Controller:
 * <pre>
 * {@code
 * @PostMapping
 * public ResponseEntity<ProductDto> createProduct(
 *         @Valid @RequestBody CreateProductRequest request) {
 *     // @Valid triggers validation
 *     ProductDto createdProduct = productService.createProduct(request);
 *     return ResponseEntity.status(HttpStatus.CREATED).body(createdProduct);
 * }
 * }
 * </pre>
 * 
 * Conversion to Entity:
 * <pre>
 * {@code
 * Product entity = new Product();
 * entity.setProductName(request.getProductName());
 * entity.setPrice(request.getPrice());
 * entity.setDescription(request.getDescription());
 * entity.setQuantity(request.getQuantity());
 * entity.setCategory(Category.valueOf(request.getCategory()));
 * // ID is auto-generated by database
 * }
 * </pre>
 * 
 * @see ProductDto
 * @see UpdateProductRequest
 * @see com.flogin.entity.Product
 * @see com.flogin.entity.Category
 */
/**
 * CreateProductRequest - DTO cho việc tạo product mới
 * Không có field id vì id được tự động generate
 */
public class CreateProductRequest {
    
    @NotBlank(message = "Product Name không được rỗng")
    @Size(min = 3, max = 100, message = "Product Name phải từ 3 đến 100 ký tự")
    private String productName;
    
    @NotNull(message = "Price không được để trống")
    @DecimalMin(value = "0.01", message = "Price phải > 0")
    @DecimalMax(value = "999999999", message = "Price không được vượt quá 999,999,999")
    private Double price;
    
    @Size(max = 500, message = "Description không được quá 500 ký tự")
    private String description;
    
    @NotNull(message = "Quantity không được để trống")
    @Min(value = 0, message = "Quantity phải >= 0")
    @Max(value = 99999, message = "Quantity không được vượt quá 99,999")
    private Integer quantity;
    
    @NotBlank(message = "Category không được rỗng")
    private String category;

    // Constructor mặc định
    public CreateProductRequest() {
    }

    public CreateProductRequest(String productName, Double price, String description, Integer quantity, String category) {
        this.productName = productName;
        this.price = price;
        this.description = description;
        this.quantity = quantity;
        this.category = category;
    }

    // Getters and Setters
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}
