package com.flogin.dto.ProductDtos;

import com.flogin.entity.Product;
import jakarta.validation.constraints.*;

import java.math.BigDecimal;

/**
 * ProductDto - Data Transfer Object for Product Representation
 * 
 * Purpose:
 * This DTO represents product data sent to/from the client application.
 * It serves as the response body for product-related API endpoints and provides
 * a clean separation between the domain model and API layer.
 * 
 * Design Pattern: DTO (Data Transfer Object)
 * - Decouples internal entity structure from external API
 * - Provides versioning flexibility for API evolution
 * - Prevents over-fetching of data
 * - Documents API response structure
 * 
 * Use Cases:
 * 1. API Response - Return product data after CRUD operations
 * 2. Product List - Return array of products in search/filter results
 * 3. Product Details - Display full product information
 * 4. Shopping Cart - Include product data with cart items
 * 
 * Fields:
 * 
 * id (long)
 * - Unique identifier from database
 * - Auto-generated by database (IDENTITY strategy)
 * - Used for subsequent update/delete operations
 * - Example: 12345
 * 
 * productName (String)
 * - Product display name
 * - @NotBlank, @Size(min=3, max=100)
 * - Searchable and sortable field
 * - Example: "Laptop Dell XPS 15", "iPhone 15 Pro Max"
 * 
 * price (Double)
 * - Product price in VND (Vietnamese Dong)
 * - @NotNull, @DecimalMin("0.01"), @DecimalMax("999999999")
 * - Displayed with currency formatting in UI
 * - Example: 25000000.00 (25 million VND)
 * 
 * quantity (Integer)
 * - Available stock quantity
 * - @NotNull, @Min(0), @Max(99999)
 * - 0 indicates out of stock
 * - Decremented on purchase, incremented on return
 * - Example: 50, 0 (out of stock)
 * 
 * description (String)
 * - Detailed product description
 * - @Size(max=500)
 * - Optional field (can be null or empty)
 * - Supports Vietnamese text
 * - Example: "Laptop cao cấp dành cho lập trình viên và designer"
 * 
 * category (String)
 * - Product category from Category enum
 * - @NotBlank
 * - Used for filtering and categorization
 * - Values: "Điện tử", "Thời trang", "Thực phẩm", "Đồ gia dụng", "Sách"
 * 
 * JSON Serialization Example:
 * <pre>
 * {
 *   "id": 12345,
 *   "productName": "Laptop Dell XPS 15",
 *   "price": 25000000.00,
 *   "description": "Laptop cao cấp cho lập trình viên",
 *   "quantity": 50,
 *   "category": "Điện tử"
 * }
 * </pre>
 * 
 * List Response Example (GET /api/products):
 * <pre>
 * {
 *   "content": [
 *     {
 *       "id": 1,
 *       "productName": "Laptop Dell",
 *       "price": 25000000.00,
 *       "quantity": 50,
 *       "category": "Điện tử",
 *       "description": "..."
 *     },
 *     {
 *       "id": 2,
 *       "productName": "Áo Polo",
 *       "price": 350000.00,
 *       "quantity": 100,
 *       "category": "Thời trang",
 *       "description": "..."
 *     }
 *   ],
 *   "pageable": { ... },
 *   "totalElements": 50,
 *   "totalPages": 5
 * }
 * </pre>
 * 
 * Constructors:
 * 
 * 1. No-arg Constructor:
 *    - Required for Jackson JSON deserialization
 *    - Used by Spring to create instances from JSON
 * 
 * 2. Full Constructor (with ID):
 *    - Used when converting from existing Entity
 *    - Includes database-generated ID
 * 
 * 3. Constructor without ID:
 *    - Used for creating DTO before persistence
 *    - ID will be set after save operation
 * 
 * Conversion from Entity:
 * <pre>
 * {@code
 * // Manual conversion
 * Product entity = productRepository.findById(id).orElseThrow();
 * ProductDto dto = new ProductDto(
 *     entity.getId(),
 *     entity.getCategory().name(),
 *     entity.getPrice(),
 *     entity.getProductName(),
 *     entity.getDescription(),
 *     entity.getQuantity()
 * );
 * 
 * // Or using mapper library (ModelMapper, MapStruct)
 * ProductDto dto = modelMapper.map(entity, ProductDto.class);
 * }
 * </pre>
 * 
 * Validation Usage:
 * While this DTO includes validation annotations, they are primarily used:
 * - For documentation purposes
 * - For potential client-side validation scenarios
 * - Input validation is done via CreateProductRequest/UpdateProductRequest
 * 
 * API Endpoints Using This DTO:
 * - GET /api/products - Returns Page<ProductDto>
 * - GET /api/products/{id} - Returns ProductDto
 * - POST /api/products - Returns ProductDto (201 Created)
 * - PUT /api/products/{id} - Returns ProductDto (200 OK)
 * - GET /api/products/search?name=laptop - Returns Page<ProductDto>
 * - GET /api/products?category=Điện%20tử - Returns Page<ProductDto>
 * 
 * Thread Safety:
 * This class is mutable (has setters) and NOT thread-safe.
 * Each request should use a new instance.
 * 
 * @see Product
 * @see CreateProductRequest
 * @see UpdateProductRequest
 * @see com.flogin.entity.Category
 */
public class ProductDto {

    private long id;
    
    @NotNull(message = "Price không được để trống")
    @DecimalMin(value = "0.01", message = "Price phải > 0")
    @DecimalMax(value = "999999999", message = "Price không được vượt quá 999,999,999")
    private Double price;
    
    @NotBlank(message = "Product Name không được rỗng")
    @Size(min = 3, max = 100, message = "Product Name phải từ 3 đến 100 ký tự")
    private String productName;
    
    @NotNull(message = "Quantity không được để trống")
    @Min(value = 0, message = "Quantity phải >= 0")
    @Max(value = 99999, message = "Quantity không được vượt quá 99,999")
    private Integer quantity;
    
    @Size(max = 500, message = "Description không được quá 500 ký tự")
    private String description;
    
    @NotBlank(message = "Category không được rỗng")
    private String category;

    // Constructor mặc định (bắt buộc cho Jackson deserialization)
    public ProductDto() {
    }

    public ProductDto(long id, String category, Double price, String productName, String description, Integer quantity) {
        this.id = id;
        this.category = category;
        this.price = price;
        this.productName = productName;
        this.description = description;
        this.quantity = quantity;
    }

    public ProductDto(String productName, Double price, String description, Integer quantity, String category) {
        this.category = category;
        this.price = price;
        this.productName = productName;
        this.description = description;
        this.quantity = quantity;
    }

    public long getId() {
        return id;
    }

    public String getCategory() {
        return category;
    }

    public String getDescription() {
        return description;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public String getProductName() {
        return productName;
    }

    public Double getPrice() {
        return price;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setCategory(String category) {
        this.category = category;
    }
}
